# Generated by Django 2.2.3 on 2019-08-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='repo',
            constraint=models.UniqueConstraint(fields=('name',), name='name-unique'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('url',), name='url-unique'),
        ),
    ]
