version: '3.7'

services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    app:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - ./app:/app
      ports:
        - "127.0.0.1:8080:8000"
      depends_on:
        - db
      environment:
        - DEBUG=1

    rabbitmq:
      image: rabbitmq

    celery:
      command: celery --app=django_thecodebase worker --loglevel=info
      build: .
      depends_on:
        - app
        - rabbitmq
      environment:
        - DEBUG=1




