version: '3.7'

services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    app:
      ports:
        - "127.0.0.1:8000:8000"
      build: .
      depends_on:
        - db
      env_file:
        - prod.env

    rabbitmq:
      image: rabbitmq

    celery:
      command: celery --app=django_thecodebase worker --loglevel=info
      build: .
      depends_on:
        - app
        - rabbitmq
      env_file:
        - prod.env


