version: '3.7'

services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    app:
      build: .
      volumes:
        - static_data:/vol/web
      ports:
        - "8000:8000"
      depends_on:
        - db
      environment:
        - SECRET_KEY=SECRET
        - ALLOWED_HOSTS=127.0.0.1,localhost

    proxy:
      build:
        context: ./proxy
      volumes:
        - static_data:/vol/static
      ports:
        - "8080:8080"
      depends_on:
        - app


volumes:
  static_data:
