version: '3.7'

services:
    thecodebase:
      build: .
      volumes:
        - ./thecodebase:/thecodebase
      env_file:
        - thecodebase.env
      network_mode: "host" # this will expose port 8000 to the codebase service and also expose postgres 5432 to thecodebase
      # ports:
      #   - 127.0.0.1:8000:8000
      # pdb debug
      # stdin_open: true
      # tty: true

    rabbitmq:
      image: rabbitmq

    celery:
      build: .
      volumes:
        - ./thecodebase:/thecodebase
      depends_on:
        - thecodebase
        - rabbitmq
      environment:
        - CELERY=1
      env_file:
        - thecodebase.env
