version: '3.7'

services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    app:
      ports:
        - "127.0.0.1:8000:8000"
      build: .
      depends_on:
        - db
      environment:
        - SECRET_KEY=SECRET
        - ALLOWED_HOSTS=127.0.0.1,localhost

    rabbitmq:
      image: rabbitmq

    celery:
      command: celery --app=django_thecodebase worker --loglevel=info
      build: .
      depends_on:
        - app
        - rabbitmq
      environment:
        - SECRET_KEY=SECRET
        - ALLOWED_HOSTS=127.0.0.1,localhost


