version: '3.7'

services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=thecodebase
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_HOST_AUTH_METHOD=trust
      volumes:
      - postgres_data:/var/lib/postgresql/data/
    app:
      build: .
      volumes:
        - ./app:/app
      ports:
        - 8000:8000
      depends_on:
        - db
      env_file:
        - app.env

    rabbitmq:
      image: rabbitmq

    celery:
      command: celery --app=django_thecodebase worker --loglevel=info
      build: .
      depends_on:
        - app
        - rabbitmq
      env_file:
        - app.env


volumes:
  postgres_data: