# Generated by Django 3.0.4 on 2020-03-21 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=30)),
                ('image_url', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('sequence', models.IntegerField(default=100)),
            ],
            options={
                'ordering': ('sequence', 'title'),
            },
        ),
        migrations.CreateModel(
            name='JavaScriptFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('sequence', models.IntegerField(default=100)),
            ],
            options={
                'ordering': ('sequence',),
            },
        ),
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('display_name', models.CharField(max_length=150)),
                ('readme_html', models.TextField()),
                ('sequence', models.IntegerField(default=100)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('no_update', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('sequence', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=30)),
                ('image_url', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('sequence', models.IntegerField(default=100)),
                ('repos', models.ManyToManyField(to='main.Repo')),
            ],
            options={
                'ordering': ('sequence', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-score', '-time'),
            },
        ),
        migrations.AddConstraint(
            model_name='repo',
            constraint=models.UniqueConstraint(fields=('name',), name='name-unique'),
        ),
        migrations.AddField(
            model_name='javascriptfile',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Game'),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.UniqueConstraint(fields=('url',), name='game-url-unique'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('url',), name='topic-url-unique'),
        ),
    ]
