# Generated by Django 2.2.4 on 2019-08-25 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', 'content_0002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ('-score', '-time')},
        ),
    ]
