# Generated by Django 2.2.4 on 2019-08-10 11:49

from django.db import migrations


def create_platform_game(apps, schema_editor):
    Game = apps.get_model('games', 'Game')
    platform_base = 'games/phaser-games/platform-game'
    platform_game = Game.objects.create(
        title='Platform Game',
        url='platform-game',
        image_url=f'{platform_base}/docs/platform_game.png',
        description="Collect as many starts as you can, but beware of the bombs! "
                    "See if you can get the highest score.",
        sequence=10,
    )
    platform_game.javascriptfile_set.create(
        path=f'{platform_base}/config.js',
        sequence=10,
    )
    platform_game.javascriptfile_set.create(
        path=f'{platform_base}/Preloader.js',
        sequence=20,
    )
    platform_game.javascriptfile_set.create(
        path=f'{platform_base}/Leaderboard.js',
        sequence=30,
    )
    platform_game.javascriptfile_set.create(
        path=f'{platform_base}/GamePlay.js',
        sequence=40,
    )


def create_eat_game(apps, schema_editor):
    Game = apps.get_model('games', 'Game')
    eatgame_base = 'games/phaser-games/eat-game'
    eat_game = Game.objects.create(
        title='Eat Game',
        url='eat-game',
        image_url=f'{eatgame_base}/docs/eat_game.png',
        description="Eat the baddies when they are vulnerable, "
                    "but watch out when they're not!",
        sequence=20,
    )
    eat_game.javascriptfile_set.create(
        path=f'{eatgame_base}/config.js',
        sequence=10,
    )
    eat_game.javascriptfile_set.create(
        path=f'{eatgame_base}/eat-game.js',
        sequence=20,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_platform_game),
        migrations.RunPython(create_eat_game),
    ]
